version: '3'

volumes:
  mariadb:

services:

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel

  app:
    image: hitalos/laravel:latest
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=SomeRandomStringSomeRandomString
      - APP_URL=http://localhost
      - APP_LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
